FROM ubuntu:latest
# or FROM ubuntu:17.04

# We assume the git repo's cloned outside and copied in, instead of
# cloning it in here. But that works, too.
WORKDIR /opt

LABEL MAINTAINER "Yang Liu"

# RUN chmod 755 Mirror_conf.sh \
# && ./Mirror_conf.sh

# Needed for add-apt-repository, et al.
#
# If you're installing this outside Docker you may not need this.
RUN apt-get update \
        && apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
        
COPY resource .
RUN cp ubuntu.sources /etc/apt/sources.list.d/
RUN apt-get update

# ubuntu:22.04 has gcc-11
RUN apt-get install -y libgccjit0 libgccjit-11-dev

# Needed for fast JSON and the configure step
RUN apt-get install -y libjansson4 libjansson-dev git

# Shut up debconf as it'll fuss over postfix for no good reason
# otherwise. If you're doing this outside Docker, you do not need to
# do this.
ENV DEBIAN_FRONTEND=noninteractive

# Cheats' way of ensuring we get all the build deps for Emacs without
# specifying them ourselves. Enable source packages then tell apt to
# get all the deps for whatever Emacs version Ubuntu supports by
# default.
RUN apt-get build-dep -y emacs

# Needed for compiling libgccjit or we'll get cryptic error messages
# about failing smoke tests.
RUN tar -xf emacs-*.tar.xz
RUN cd emacs-*/ && ./autogen.sh

# Configure and run
RUN cd emacs-*/ && ./configure --with-native-compilation --with-mailutils --with-json

ENV JOBS=2
RUN cd emacs-*/ && make -j ${JOBS} && make install

# ------------------------------ TODO: refactor ------------------------------

# 设置环境变量，避免提示区域选择等问题
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8

# 更新包管理器并安装必要的软件包
RUN apt-get update && apt-get install -y \
    locales \            
    fonts-wqy-zenhei \
    fonts-wqy-microhei && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 配置中文语言环境
RUN locale-gen zh_CN.UTF-8 && \
    update-locale LANG=zh_CN.UTF-8

# x11-apps 包含一些简单的 X11 应用程序（用于测试 GUI）
# xauth用于 X11 转发
# mesa-utils包含 `glxinfo` 和 `glxgears` 等测试工具
# libgl1-mesa-glx提供 OpenGL 支持
# libx*提供 X11 依赖
RUN apt-get update && apt-get install -y \
    x11-apps \  
    xauth \      
    mesa-utils \ 
    libgl1 \ 
    libxrender1 libxtst6 libxi6 \ 
    vim wget curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/bash"]
